(define (main)
  (display (> 3 2))
  (newline)
  (display (< 3 2))
  (newline)
  (display (>= 3 3))
  (newline)
  (display (<= 4 3))
  (newline)
  (display (= 5 5))
  (newline)
  (display (<> 5 5))
  (newline))