(define x 100)

(define (main)
  (display x)
  (newline)
  (let ((x 50))
    (display x)
    (newline)
    (let ((x 10) (y 5))
      (display x)
      (newline)
      (display y)
      (newline)))
  (display x)
  (newline))