(define x 100)

(define (main)
  (display x)
  (newline)
  (let ((x 5) (y 3))
    (display x)
    (newline)
    (display y)
    (newline)
    (display (+ x y))
    (newline))
  (display x)
  (newline))