(define (main)
  (display "Introduce dos numeros:")
  (newline)
  (let ((n1 (read))
        (n2 (read)))
     (display "Suma: ")
     (display (+ n1 n2))
     (newline)
     (display "Producto: ")
     (display (* n1 n2))
     (newline)))